# Dockerfile.prod

FROM tomcat:10.1-jdk17-temurin

# Copy the WAR file from the volume (docker-compose will mount /input)
COPY /input/hello-*.war /usr/local/tomcat/webapps/hello.war

# Assign a port and start Catalina
EXPOSE 8080
CMD ["catalina.sh", "run"]