---
- name: Replace default nginx page
  hosts: 
  become: yes

  vars:
    custom_message: "Hello from Ansible-managed nginx!"

  tasks:
    - name: Install nginx
      package:
        name: nginx
        state: present

    - name: Replace default page content
      lineinfile:
        path: /var/www/html/index.html
        regexp: '<p>If you see this page, the nginx web server is successfully installed and working. Further configuration is required.</p>'
        line: '<p>{{ custom_message }}</p>'
        backup: yes
      notify: Restart nginx

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
