# Homework 6 - JAVA Project 

FROM ubuntu:20.04
MAINTAINER Sherali Turabov <turabov.sh@gmail.com>

# Переменные окружения (отключает интерактивные диалоги)
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Moscow

RUN apt-get update && apt-get install -y wget git default-jdk maven